### ISSUE TITLE
Use of deprecated `getTestClassesDir()` method

### ISSUE THREAD

**Issue by mvondracek** [crocs-muni/javacard-gradle-template-edu#3]
Following deprecation warning is shown when gradle project is loaded to InteliJ IDEA. This occurs on tag `v0.2.1-edu` and `v0.2.0-edu`.
~~~
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
~~~

**Comment by ph4r05** [comment]
can you pls try to pull and verify if this problem persists?

**Comment by ph4r05** [comment]
if yes, pls reopen the issue, thanks!
