### ISSUE TITLE
Incompatibility with JCMathLib 1.0.1

### ISSUE THREAD

**Issue by mvondracek** [crocs-muni/javacard-gradle-template-edu#5]
Hello, I found a strange bug which makes this template incompatible with [JCMathLib](https://github.com/OpenCryptoProject/JCMathLib).

I tried to use [JCMathLib 1.0.1](https://github.com/OpenCryptoProject/JCMathLib/releases/tag/v1.0.1). Method `ECPoint#multiplication` hangs in [`jcmathlib.jcmathlib.Bignat.sqrt_FP` on line 1709 in while loop](https://github.com/mvondracek/javacard-gradle-template-edu/blob/954ae032226b8166c6964397b3fe2211e9cc6e44/applet/src/main/java/jcmathlib/jcmathlib.java#L1709-L1712). I first thought this is a bug in JCMathLib, but I cannot replicate this issue when using JCMathLib for applet without this template.

So to isolate this issue I used fork of this repository, branched from master, added JCMathLib 1.0.1 in compact single file form, and added [tests which demonstrate that `ECPoint#multiplication` hangs both while running in JUnit and in simulated applet](https://github.com/mvondracek/javacard-gradle-template-edu/blob/954ae032226b8166c6964397b3fe2211e9cc6e44/applet/src/test/java/jcmathlib/jcmathlibTest.java). Here are the changes to demonstrate this issue. https://github.com/crocs-muni/javacard-gradle-template-edu/compare/master...mvondracek:jcmathlib

Any idea what's wrong? Are there any incompatible changes between official jCardSim and `com.klinec:jcardsim:3.0.5.9`?

**Comment by ph4r05** [comment]
TBH no idea. @petrs any thoughts?

**Comment by ph4r05** [comment]
ping @mvondracek, do you have any new info/insights? I am way too busy to debug this on my own atm.

**Comment by ph4r05** [comment]
try bumping jcardsim to `3.0.5.11` and set 

```java
System.setProperty("com.licel.jcardsim.randomdata.secure", "1");
```

before loading the applet to the simulator.

**Comment by petrs** [comment]
hmm, no idea - but there is some new work planned for JCMathLib (adding support for cards with PLAIN_XY KeyAgreemnt which will speedup operations a lot) and we can check this issue while doing it

**Comment by ph4r05** [comment]
Also, try:
- try bumping jcardsim to `3.0.5.11`
- bumping gradle plugin to `1.7.2`
- set:

```java
System.setProperty("com.licel.jcardsim.randomdata.secure", "1");
```

**Comment by mvondracek** [comment]
Hello, thank you for your suggestions! I updated [branch with bug example](https://github.com/mvondracek/javacard-gradle-template-edu/tree/jcmathlib), but it did not solve the problem. 

Unfortunately, I do not have time to debug it at the moment, neither. Our team was working on [PV204 project](https://github.com/mvondracek/PV204_smartcards_Emerald) while we detected this issue. So as our work on the project is finished, this is more of a bug report than critical problem blocking our team.

So at least this can be a note to future users that JCMathLib does not work with this template for now... Thanks anyway.

**Comment by dufkan** [comment]
Hi, this issue should now be fixed in JCMathLib (OpenCryptoProject/JCMathLib#23) when `bIsSimulator` flag is set.

More recent versions of jCardSim (including those in this template) have problems with some underlying operations used to implement multiplication and point doubling. When `bIsSimulator` flag is set, JCMathLib avoids these operations and should work in the simulator as expected.

**Comment by ph4r05** [comment]
Closing issue, in case of a regression, reopen pls. 
Thanks @dufkan
