### ISSUE TITLE
Supported Java versions

### ISSUE THREAD

**Issue by xskrasek** [crocs-muni/javacard-gradle-template-edu#7]
Which versions are supported? It is probably obvious to people working with JavaCards, but I had no idea. I managed to find out from one of the commits, but it would be nice, if there was a part in readme for this.

**Comment by ph4r05** [comment]
We can link the following document in the readme: https://github.com/martinpaljak/ant-javacard/wiki/Version-compatibility

Java compatibility depends on SDK being used. Java 8 should be the best for majority of setups.

**Comment by xskrasek** [comment]
That would be great. I was not aware of the repository and it having the information as I am new to all of this.
