### ISSUE TITLE
Certificate issue during gradle.bat execution

### ISSUE THREAD

**Issue by xskrasek** [crocs-muni/javacard-gradle-template-edu#8]
When I tried to run gradle.bat, I got the following error:

```
* What went wrong:
A problem occurred configuring project ':applet'.
> Could not resolve all artifacts for configuration ':applet:classpath'.
   > Could not download ant-javacard-20.03.25.jar (com.github.martinpaljak:ant-javacard:20.03.25)
      > Could not get resource 'https://javacard.pro/maven/com/github/martinpaljak/ant-javacard/20.03.25/ant-javacard-20.03.25.jar'.
         > Could not GET 'https://javacard.pro/maven/com/github/martinpaljak/ant-javacard/20.03.25/ant-javacard-20.03.25.jar'.
            > peer not authenticated
```
I could fix this by importing the certificate manually. However I am not sure, if this is something you can fix. 
OS: Windows

**Comment by ph4r05** [comment]
certificate is perfectly fine according to my browsers, make sure you have up to date java.
Older versions of java8 could have a problem with some certificate roots. You need to have at least java8 update 271.

**Comment by ph4r05** [comment]
Cannot replicate on `java version "1.8.0_271"`, closing the issue.
